import Head from 'next/head'
import Header from '@/components/home/Header'
import InfoInputForm from '@/components/home/InfoInputForm'
import { useRef, useState } from 'react'

export default function Home() {
  const [email, setEmail] = useState("");
  const [phone, setPhone] = useState("");
  const [ages, setAges] = useState("");
  const [sex, setSex] = useState("");

  const phoneRef = useRef(null);

  const onChangePhone = ()=>{}

  return (
    <>
      <Head>
        <title>Survey Temp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div >
        <InfoInputForm 
          email={email}
          setEmail={setEmail}
          phone={phone}
          phoneRef={phoneRef}
          onChangePhone={onChangePhone}
          ages={ages}
          setAges={setAges}
          sex={sex}
          setSex={setSex}
        />
      </div>
    </>
  )
}
