import Head from 'next/head'
import Header from '@/components/home/Header'
import InfoInputForm from '@/components/home/InfoInputForm'
import { ChangeEvent, useRef, useState } from 'react'
import Privacy from '@/components/home/Privacy';
import styles from "@/styles/Home.module.css";

export default function Home() {
  const [email, setEmail] = useState("");
  const [phone, setPhone] = useState("");
  const [ages, setAges] = useState("");
  const [sex, setSex] = useState("");

  const phoneRef = useRef<HTMLInputElement>(null);

  const onChangePhone = (e: ChangeEvent<HTMLInputElement>) => {
    if (phoneRef.current) {
      const value = phoneRef.current.value.replace(/\D+/g, "");
      const phoneLength = 11;
      let result = "";
      for (let i = 0; i < value.length && i < phoneLength; i++) {
        switch (i) {
          case 3:
            result += "-";
            break;
          case 7:
            result += "-";
            break;
          default:
            break;
        }
        result += value[i];
      }
      phoneRef.current.value = result;
      setPhone(e.target.value);
    }
  }

  return (
    <>
      <Head>
        <title>Survey Temp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <div className={styles.wrapper}>
          <InfoInputForm
            email={email}
            setEmail={setEmail}
            phone={phone}
            phoneRef={phoneRef}
            onChangePhone={onChangePhone}
            ages={ages}
            setAges={setAges}
            sex={sex}
            setSex={setSex}
          />
          <Privacy />
        </div>
      </main>
    </>
  )
}
